name: ${name}
version: ${version}
main: ${main}
api-version: "1.21"
loader: "io.papermc.paper.plugin.loader.DefaultPluginLoader"
author: sora
commands:
  giveitem:
    description: Give a custom item by id
    usage: /giveitem <id> [player]
    permission: itemcreator.give
  createrecipe:
    description: Open the recipe creator interface
    usage: /createrecipe
    permission: itemcreator.createrecipe
  recipes:
    description: Manage existing recipes
    usage: /recipes
    permission: itemcreator.recipes
  itemcreator:
    description: ItemCreator main command (reload)
    usage: /itemcreator <reload>
    permission: itemcreator.admin
  abilities:
    description: Manage item abilities through GUI
    usage: /abilities <item_id>
    permission: itemcreator.abilities
permissions:
  itemcreator.give:
    default: op
  itemcreator.createrecipe:
    default: op
    description: Create custom recipes using the GUI interface
  itemcreator.recipes:
    default: op
    description: View and manage existing recipes
  itemcreator.admin:
    default: op
    description: Use ItemCreator admin commands like reload
  itemcreator.abilities:
    default: op
    description: Manage item abilities through the GUI
